# Generated by Django 3.1.4 on 2020-12-21 09:20

import apps.registration_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.registration_profile.models.code_generator, max_length=5)),
            ],
        ),
    ]
