# Generated by Django 3.1.5 on 2021-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_profile', '0002_registrationprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
