# Generated by Django 3.1.5 on 2021-01-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_profile', '0004_remove_registrationprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
    ]
