# Generated by Django 3.1.4 on 2020-12-30 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='FriendRequest',
        ),
    ]
